# --- General options --- #

# url is the full website URL
# baseurl is the website's URL without the hostname

# If you are building a simple GitHub user page (http://username.github.io) then use these settings:
url: "https://vietanhdev.com"
baseurl: ""

# If you are building a GitHub project page then use these settings:
#url: "http://username.github.io/projectname"
#baseurl: "/projectname"

# Of course don't forget to change the username and projectname to YOUR username and project

# Name of website
title: Nguyễn Việt Anh

# Short description of your site
description: Viet Anh Nguyen's Homepage, where I share with the world about my life and my work

# --- Navigation bar options --- #

navbar-links:
  Home: ""
  My Blog: blog/
  My Projects: projects/
  Contact: contact/
nav-search: search/

# --- Footer options --- #

# Change all these values or delete the ones you don't want.
# Important: you must keep the "name" parameter, everything else you can remove
author:
  name: Viet Anh Nguyen
  email: "vietanh@vietanhdev.com"
  facebook: vietanhdev  # eg. vietanhdev
  github: vietanhdev    # eg. vietanhdev
  twitter: vietanhdev   # eg. vietanhdev
  google-plus: +vietanhdev   # eg. +DeanAttali or 109424658772469020925
  stackoverflow: vietanhdev  # eg. "3943160/vietanhdev"
  #linkedin: vietanhdev  # eg. vietanhdev
  #xing: vietanhdev      # eg. vietanhdev
  #snapchat: vietanhdev  # eg. vietanhdev
  #instagram: vietanhdev # eg. vietanhdev
  #youtube: vietanhdev   # eg. user/vietanhdev or channel/vietanhdev
  #spotify: vietanhdev   # eg. vietanhdev

# Select which links to show in the footer
footer-links-active:
  rss: true
  facebook: true
  email: true
  twitter: false
  google-plus: false
  github: true
  linkedin: false
  xing: false
  stackoverflow: false
  snapchat: false
  instagram: false
  youtube: false
  spotify: false

# Select which share links to show in posts
share-links-active:
  twitter: true
  facebook: true
  google: true
  linkedin: true

# How to display the link to the website in the footer
# Remove this if you don't want a link in the footer
url-pretty: "VietAnhDev.com"

# --- Misc --- #

# Fill in your Google Analytics ID to track your website using GA
google_analytics: "UA-78251251-1"

# Facebook App ID
fb_app_id: "1794997907410583"

# --- Don't need to touch anything below here (but you can if you want) --- #

# Output options (more information on Jekyll's site)
timezone: "+0700"
permalink: /blog/:title/
paginate: 5

markdown: kramdown
# !github-pages! mandatory › https://help.github.com/articles/using-jekyll-with-pages/#configuration-settings-you-cannot-change
# Since Jekyll 3 the default highlighter is Rouge (replaced Pygments.rb in v44)
highlighter: rouge

# More › http://kramdown.gettalong.org/quickref.html
# Options › http://kramdown.gettalong.org/options.html
kramdown:
  input:          GFM
  # https://github.com/jekyll/jekyll/pull/4090
  syntax_highlighter: rouge

  # Rouge Highlighter in Kramdown › http://kramdown.gettalong.org/syntax_highlighter/rouge.html
  # span, block element options fall back to global
  syntax_highlighter_opts:
    # Rouge Options › https://github.com/jneen/rouge#full-options
    css_class: 'highlight'
    #line_numbers: true # bad idea, spans don't need linenos and would inherit this option
    span:
      line_numbers: false
    block:
      line_numbers: true
      start_line: 1

# Default YAML values (more information on Jekyll's site)
defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
      comments: true  # add comments to all blog posts
      social-share: true # add social media sharing buttons to all blog posts
  -
    scope:
      path: "" # all files
    values:
      layout: "page"

# Use tags pages (not recommended if you are deploying via GitHub pages, only set to true if deploying locally with ruby)
link-tags: false

# Exclude these files from production site
exclude:
  - Gemfile
  - Gemfile.lock
  - LICENSE
  - README.md
  - CNAME
  - Vagrantfile

gems:
  - jekyll-paginate
